backend:
  name: git-gateway
  branch: develop
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "pages"
    label: "Pages"
    files:
      - file: 'src/pages/index.md'
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: SEO,
              name: seo,
              widget: object,
              fields:
                [
                  { label: Author, name: author, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Keywords, name: keywords, widget: string },
                  { label: Title, name: title, widget: string },
                ]
            }
          - {
              label: Hero Panel,
              name: heroPanel,
              widget: object,
              fields:
                [
                  { label: Dark Mode, name: darkMode, widget: boolean, default: false },
                  {
                    label: Background,
                    name: imageBg,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: SEO - Image Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Title Highlight, name: titleHighlight, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  { label: Button, name: button, widget: string },
                ],
            }
          - {
              label: Apply Panel,
              name: applyPanel,
              widget: object,
              fields:
                [
                  { label: Dark Mode, name: darkMode, widget: boolean, default: false },
                  {
                    label: Background,
                    name: imageBg,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: SEO - Image Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  { label: Button, name: button, widget: string },
                ],
            }
      - file: 'src/pages/team/index.md'
        label: 'Team Page'
        name: 'team'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'team-page',
            }
          - {
              label: SEO,
              name: seo,
              widget: object,
              fields:
                [
                  { label: Author, name: author, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Keywords, name: keywords, widget: string },
                  { label: Title, name: title, widget: string },
                ]
            }
          - {
              label: Hero Panel,
              name: heroPanel,
              widget: object,
              fields:
                [
                  { label: Dark Mode, name: darkMode, widget: boolean, default: false },
                  {
                    label: Background,
                    name: imageBg,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: SEO - Image Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Title Highlight, name: titleHighlight, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  { label: Button, name: button, widget: string },
                ],
            }
      - file: 'src/pages/partners/index.md'
        label: 'Partners Page'
        name: 'partners'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'partners-page',
            }
          - {
              label: SEO,
              name: seo,
              widget: object,
              fields:
                [
                  { label: Author, name: author, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Keywords, name: keywords, widget: string },
                  { label: Title, name: title, widget: string },
                ]
            }
          - {
              label: Hero Panel,
              name: heroPanel,
              widget: object,
              fields:
                [
                  { label: Dark Mode, name: darkMode, widget: boolean, default: false },
                  {
                    label: Background,
                    name: imageBg,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: SEO - Image Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Title Highlight, name: titleHighlight, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  { label: Button, name: button, widget: string },
                ],
            }
          - {
              label: Partners Panel,
              name: partnersPanel,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  {
                    label: Partners,
                    name: partners,
                    widget: list,
                    fields:
                      [
                        {
                          label: Logo,
                          name: partnerImage,
                          widget: object,
                          fields:
                            [
                              { label: Image, name: image, widget: image },
                            ],
                        },
                        { label: Name, name: name, widget: text },
                        { label: Link, name: link, widget: string },
                      ],
                  },

                ],
            }
          - {
              label: Apply Panel,
              name: applyPanel,
              widget: object,
              fields:
                [
                  { label: Dark Mode, name: darkMode, widget: boolean, default: false },
                  {
                    label: Background,
                    name: imageBg,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: SEO - Image Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  { label: Button, name: button, widget: string },
                ],
            }
      - file: 'src/pages/our-values/index.md'
        label: 'Our Values Page'
        name: 'our-values'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'our-values-page',
            }
          - {
              label: SEO,
              name: seo,
              widget: object,
              fields:
                [
                  { label: Author, name: author, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Keywords, name: keywords, widget: string },
                  { label: Title, name: title, widget: string },
                ]
            }
          - {
              label: Hero Panel,
              name: heroPanel,
              widget: object,
              fields:
                [
                  { label: Dark Mode, name: darkMode, widget: boolean, default: false },
                  {
                    label: Background,
                    name: imageBg,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: SEO - Image Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Title Highlight, name: titleHighlight, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  { label: Button, name: button, widget: string },
                ],
            }
          - {
              label: Our Values Panel,
              name: ourValuesPanel,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  {
                    label: Values,
                    name: values,
                    widget: list,
                    fields:
                      [
                        {
                          label: Image,
                          name: valueImage,
                          widget: object,
                          fields:
                            [
                              { label: Image, name: image, widget: image },
                              { label: SEO - Image Description, name: alt, widget: string },
                            ],
                        },
                        { label: Title, name: title, widget: text },
                        { label: Detail, name: paragraph, widget: string },
                      ],
                  },

                ],
            }
          - {
              label: Apply Panel,
              name: applyPanel,
              widget: object,
              fields:
                [
                  { label: Dark Mode, name: darkMode, widget: boolean, default: false },
                  {
                    label: Background,
                    name: imageBg,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: SEO - Image Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Text, name: paragraph, widget: string },
                  { label: Button, name: button, widget: string },
                ],
            }